# fly.toml app configuration file generated for directus-rh-billowing-sky-7393 on 2025-03-07T12:23:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'directus-rh-billowing-sky-7393'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8055'

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
